services:
  producer:
    build:
      dockerfile: messaging-producer-api/Dockerfile
    image: localhost:5001/producer:latest

  consumer:
    build:
      dockerfile: processing-consumer-api/Dockerfile
    image: localhost:5001/consumer:latest

  simulator:
    build:
      dockerfile: requests-simulator-api/Dockerfile
    image: localhost:5001/requests:latest