{{- if and .Values.metrics .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}-monitor
  labels:
    {{- toYaml .Values.metrics.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  endpoints:
    - port: {{ .Values.metrics.serviceMonitor.portName }}
      path: {{ .Values.metrics.serviceMonitor.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      relabelings:
        - targetLabel: instance
          replacement: {{ .Values.service.name }}
          action: replace
{{- end }}