apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requests
  template:
    metadata:
      labels:
        app: requests
    spec:
      initContainers:
        - name: wait-for-producer
          image: alpine:3.19
          command:
            - 'sh'
            - '-c'
            - |
              until wget -qO- http://producer:8080/actuator/health | grep -q '"status":"UP"'; do
                echo "Waiting for API Producer to respond with status UP..."
                sleep 3
              done
      containers:
          - name: requests
            image: requests:latest
            imagePullPolicy: Never
            env:
              - name: "APP_REQUEST_DELAY_MS"
                value: "150"
            ports:
              - containerPort: 8080