apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
data:
  providers.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        folder: 'Observability'
        type: file
        options:
          path: /var/lib/grafana/dashboards
