app:
  name: producer
  image: "producer:latest"

service:
  name: producer

initContainers:
  - name: wait-for-rabbitmq
    image: busybox:1.28
    command:
      - 'sh'
      - '-c'
      - |
        until nc -z rabbitmq 5672; do
          echo "Waiting for a connection to RabbitMQ..."
          sleep 3
        done