apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for a connection to RabbitMQ..."
                sleep 3
              done
      containers:
        - name: producer
          image: producer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080