apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          {{- if .Values.envVars }}
          env:
            {{- range .Values.envVars }}
            - name:  {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end}}
          imagePullPolicy: Never
          ports:
            - containerPort: 8080