spring.application.name=processing-consumer-api

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.multiplier=1.5

spring.rabbitmq.connection-timeout=5000ms

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always